version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql-server
  mysql-server:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userManagement
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: